import type { User, Story, Template } from '../types'

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ana Lima',
    username: 'analima',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    hasNewStory: true,
  },
  {
    id: '2',
    name: 'Bruno Souza',
    username: 'brunosouza',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bruno',
    hasNewStory: true,
  },
  {
    id: '3',
    name: 'Carla Mendes',
    username: 'carlam',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carla',
    hasNewStory: true,
  },
  {
    id: '4',
    name: 'Diego Costa',
    username: 'diegoc',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diego',
    hasNewStory: false,
  },
  {
    id: '5',
    name: 'Elena Ramos',
    username: 'elenar',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    hasNewStory: true,
  },
  {
    id: '6',
    name: 'Fábio Nunes',
    username: 'fabion',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fabio',
    hasNewStory: false,
  },
]

export const mockStories: Story[] = [
  {
    id: 's1',
    userId: '1',
    user: mockUsers[0],
    frames: [
      {
        id: 'f1',
        backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        textElements: [
          {
            id: 't1',
            content: 'Bom dia! ☀️',
            x: 50,
            y: 40,
            fontSize: 36,
            fontFamily: 'Inter',
            color: '#ffffff',
            rotation: 0,
            bold: true,
            italic: false,
          },
        ],
        stickers: [],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'f2',
        backgroundColor: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        textElements: [
          {
            id: 't2',
            content: 'Novidades em breve 🚀',
            x: 30,
            y: 45,
            fontSize: 28,
            fontFamily: 'Poppins',
            color: '#ffffff',
            rotation: -5,
            bold: false,
            italic: false,
          },
        ],
        stickers: [],
        createdAt: new Date().toISOString(),
      },
    ],
    duration: 5000,
    createdAt: new Date().toISOString(),
    views: 234,
  },
  {
    id: 's2',
    userId: '2',
    user: mockUsers[1],
    frames: [
      {
        id: 'f3',
        backgroundColor: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        textElements: [
          {
            id: 't3',
            content: '50% OFF hoje! 🔥',
            x: 50,
            y: 35,
            fontSize: 42,
            fontFamily: 'Inter',
            color: '#ffffff',
            rotation: 0,
            bold: true,
            italic: false,
          },
        ],
        stickers: [],
        createdAt: new Date().toISOString(),
      },
    ],
    duration: 7000,
    createdAt: new Date().toISOString(),
    views: 1890,
  },
  {
    id: 's3',
    userId: '3',
    user: mockUsers[2],
    frames: [
      {
        id: 'f4',
        backgroundColor: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
        textElements: [
          {
            id: 't4',
            content: '"Acredite no processo"',
            x: 20,
            y: 40,
            fontSize: 24,
            fontFamily: 'Poppins',
            color: '#ffffff',
            rotation: 0,
            bold: false,
            italic: true,
          },
        ],
        stickers: [],
        createdAt: new Date().toISOString(),
      },
    ],
    duration: 5000,
    createdAt: new Date().toISOString(),
    views: 567,
  },
  {
    id: 's4',
    userId: '5',
    user: mockUsers[4],
    frames: [
      {
        id: 'f5',
        backgroundColor: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
        textElements: [
          {
            id: 't5',
            content: 'Novo produto! ✨',
            x: 50,
            y: 40,
            fontSize: 32,
            fontFamily: 'Inter',
            color: '#ffffff',
            rotation: 0,
            bold: true,
            italic: false,
          },
        ],
        stickers: [],
        createdAt: new Date().toISOString(),
      },
    ],
    duration: 5000,
    createdAt: new Date().toISOString(),
    views: 3421,
  },
]

export const mockTemplates: Template[] = [
  {
    id: 'tmpl1',
    name: 'Promoção Flash',
    category: 'promotion',
    thumbnail: '',
    backgroundColor: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    textElements: [
      {
        content: '⚡ OFERTA RELÂMPAGO',
        x: 50,
        y: 25,
        fontSize: 28,
        fontFamily: 'Inter',
        color: '#ffffff',
        rotation: 0,
        bold: true,
        italic: false,
      },
      {
        content: '50% OFF',
        x: 50,
        y: 50,
        fontSize: 72,
        fontFamily: 'Inter',
        color: '#ffffff',
        rotation: 0,
        bold: true,
        italic: false,
      },
      {
        content: 'Apenas hoje!',
        x: 50,
        y: 75,
        fontSize: 22,
        fontFamily: 'Poppins',
        color: 'rgba(255,255,255,0.85)',
        rotation: 0,
        bold: false,
        italic: false,
      },
    ],
  },
  {
    id: 'tmpl2',
    name: 'Lançamento',
    category: 'product',
    thumbnail: '',
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    textElements: [
      {
        content: '🚀 NOVO',
        x: 50,
        y: 20,
        fontSize: 20,
        fontFamily: 'Inter',
        color: 'rgba(255,255,255,0.8)',
        rotation: 0,
        bold: false,
        italic: false,
      },
      {
        content: 'Nome do Produto',
        x: 50,
        y: 45,
        fontSize: 40,
        fontFamily: 'Poppins',
        color: '#ffffff',
        rotation: 0,
        bold: true,
        italic: false,
      },
      {
        content: 'Disponível agora 👇',
        x: 50,
        y: 72,
        fontSize: 20,
        fontFamily: 'Inter',
        color: 'rgba(255,255,255,0.9)',
        rotation: 0,
        bold: false,
        italic: false,
      },
    ],
  },
  {
    id: 'tmpl3',
    name: 'Frase Motivacional',
    category: 'quote',
    thumbnail: '',
    backgroundColor: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    textElements: [
      {
        content: '"',
        x: 20,
        y: 20,
        fontSize: 80,
        fontFamily: 'DM Serif Display',
        color: 'rgba(255,255,255,0.3)',
        rotation: 0,
        bold: true,
        italic: false,
      },
      {
        content: 'Sua frase aqui',
        x: 50,
        y: 50,
        fontSize: 30,
        fontFamily: 'Poppins',
        color: '#ffffff',
        rotation: 0,
        bold: false,
        italic: true,
      },
      {
        content: '— Autor',
        x: 70,
        y: 72,
        fontSize: 18,
        fontFamily: 'Inter',
        color: 'rgba(255,255,255,0.7)',
        rotation: 0,
        bold: false,
        italic: false,
      },
    ],
  },
  {
    id: 'tmpl4',
    name: 'Anúncio',
    category: 'announcement',
    thumbnail: '',
    backgroundColor: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    textElements: [
      {
        content: '📢 ATENÇÃO',
        x: 50,
        y: 25,
        fontSize: 24,
        fontFamily: 'Inter',
        color: '#ffffff',
        rotation: 0,
        bold: true,
        italic: false,
      },
      {
        content: 'Título do Anúncio',
        x: 50,
        y: 48,
        fontSize: 38,
        fontFamily: 'Poppins',
        color: '#ffffff',
        rotation: 0,
        bold: true,
        italic: false,
      },
      {
        content: 'Saiba mais em nosso perfil',
        x: 50,
        y: 72,
        fontSize: 18,
        fontFamily: 'Inter',
        color: 'rgba(255,255,255,0.85)',
        rotation: 0,
        bold: false,
        italic: false,
      },
    ],
  },
  {
    id: 'tmpl5',
    name: 'Coleção Verão',
    category: 'product',
    thumbnail: '',
    backgroundColor: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    textElements: [
      {
        content: '☀️ VERÃO 2025',
        x: 50,
        y: 22,
        fontSize: 22,
        fontFamily: 'Inter',
        color: 'rgba(255,255,255,0.9)',
        rotation: 0,
        bold: false,
        italic: false,
      },
      {
        content: 'Nova Coleção',
        x: 50,
        y: 48,
        fontSize: 46,
        fontFamily: 'Poppins',
        color: '#ffffff',
        rotation: -3,
        bold: true,
        italic: false,
      },
      {
        content: 'Ver agora →',
        x: 50,
        y: 74,
        fontSize: 20,
        fontFamily: 'Inter',
        color: '#ffffff',
        rotation: 0,
        bold: false,
        italic: false,
      },
    ],
  },
  {
    id: 'tmpl6',
    name: 'Black Friday',
    category: 'promotion',
    thumbnail: '',
    backgroundColor: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    textElements: [
      {
        content: 'BLACK FRIDAY',
        x: 50,
        y: 28,
        fontSize: 36,
        fontFamily: 'Inter',
        color: '#f0c040',
        rotation: 0,
        bold: true,
        italic: false,
      },
      {
        content: 'ATÉ 70% OFF',
        x: 50,
        y: 52,
        fontSize: 52,
        fontFamily: 'Inter',
        color: '#ffffff',
        rotation: 0,
        bold: true,
        italic: false,
      },
      {
        content: '🛒 Aproveite agora!',
        x: 50,
        y: 75,
        fontSize: 22,
        fontFamily: 'Poppins',
        color: 'rgba(255,255,255,0.8)',
        rotation: 0,
        bold: false,
        italic: false,
      },
    ],
  },
  {
    id: 'tmpl7',
    name: 'Poster Bold',
    category: 'promotion',
    thumbnail: '',
    backgroundColor: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    textElements: [
      {
        content: 'GRANDE',
        x: 50,
        y: 32,
        fontSize: 62,
        fontFamily: 'Paytone One',
        color: '#ffffff',
        rotation: 0,
        bold: false,
        italic: false,
      },
      {
        content: 'PROMOÇÃO',
        x: 50,
        y: 52,
        fontSize: 48,
        fontFamily: 'Paytone One',
        color: '#f59e0b',
        rotation: 0,
        bold: false,
        italic: false,
      },
      {
        content: 'Aproveite agora ⚡',
        x: 50,
        y: 74,
        fontSize: 20,
        fontFamily: 'Inter',
        color: 'rgba(255,255,255,0.75)',
        rotation: 0,
        bold: false,
        italic: false,
      },
    ],
  },
  {
    id: 'tmpl8',
    name: 'Deco Elegante',
    category: 'product',
    thumbnail: '',
    backgroundColor: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%)',
    textElements: [
      {
        content: '✦ NOVA COLEÇÃO ✦',
        x: 50,
        y: 25,
        fontSize: 18,
        fontFamily: 'Poiret One',
        color: '#d4af37',
        rotation: 0,
        bold: false,
        italic: false,
      },
      {
        content: 'Elegância',
        x: 50,
        y: 48,
        fontSize: 56,
        fontFamily: 'Poiret One',
        color: '#ffffff',
        rotation: 0,
        bold: false,
        italic: false,
      },
      {
        content: '— em cada detalhe',
        x: 50,
        y: 68,
        fontSize: 20,
        fontFamily: 'Poiret One',
        color: '#d4af37',
        rotation: 0,
        bold: false,
        italic: false,
      },
    ],
  },
]

export const gradientOptions = [
  'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
  'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
  'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
  'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
  'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
  'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
  'linear-gradient(135deg, #2d2d2d 0%, #1a1a1a 100%)',
]

export interface FontOption {
  label: string
  family: string
  style?: 'neon' | 'strong' | 'default'
  preview?: string
}

export const fontOptions: FontOption[] = [
  { label: 'Clássico',    family: 'Inter',             style: 'default' },
  { label: 'Moderno',     family: 'DM Serif Display',  style: 'default' },
  { label: 'Poster',      family: 'Paytone One',        style: 'default' },
  { label: 'Deco',        family: 'Poiret One',         style: 'default' },
  { label: 'Forte',       family: 'Bebas Neue',         style: 'strong'  },
  { label: 'Máquina',     family: 'Special Elite',      style: 'default' },
  { label: 'Marcador',    family: 'Permanent Marker',   style: 'default' },
  { label: 'Cursivo',     family: 'Lobster',            style: 'default' },
  { label: 'Poppins',     family: 'Poppins',            style: 'default' },
  { label: 'Oswald',      family: 'Oswald',             style: 'strong'  },
]

export const stickerOptions = [
  '🔥', '⚡', '🚀', '✨', '💫', '❤️', '🎉', '🎊',
  '👆', '👇', '👉', '👈', '💯', '🏆', '⭐', '🌟',
  '📢', '📣', '🛒', '💰', '🎁', '🌈', '☀️', '🌙',
]
